### ISSUE TITLE
Error when Milestone is Empty

### ISSUE THREAD

**Issue by maximilianreimer** [instantish/notion-github-action#51]
<sub>[Discuss in #**public-issue-51--error-when-milestone-is-empty**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C0352LEQJG3)</sub>

**Describe the bug**
When an issue is created that does not contain milestones this error occurs: 

```
Run instantish/notion-github-action@v1.2.0
context event: issues
context action: __instantish_notion-github-action
payload action: closed
Starting...
Querying database for page with github id xxx
Query successful: Page xxx
Updating page for issue #62
Client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation: body.properties.Milestone.rich_text[0].text.content should be populated, instead was `""`.'
}
Error: body failed validation: body.properties.Milestone.rich_text[0].text.content should be populated, instead was `""`.
```

**To Reproduce**
1. Use this config:
```yaml
name: Notion Sync

on:
  workflow_dispatch:
  issues:
    types:
      [
        opened,
        edited,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        milestoned,
        demilestoned,
        reopened,
        closed,
      ]

jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: Add GitHub Issues to Notion
    steps:
      - name: Add GitHub Issues to Notion
        uses: instantish/notion-github-action@v1.2.0
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
```
2. Create an Issue without assigning a milestone.
